import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Dwayne',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Tiffin card',
        logo: '/images/logo1.jpg',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Punjabi tiffin',
      category: 'Punjabi',
      image: '/images/p1.jpg',
      price: 60,
      countInStock: 10,
      brand: 'Punjabi',
      rating: 4.5,
      numReviews: 10,
      description: 'Dal roti 5 sabji aachar papad aur rice ',
    },
    {
      name: 'Gujrati tiffin',
      category: 'Gujrati',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Gujrati',
      rating: 4.0,
      numReviews: 10,
      description: 'Dal roti 5 sabji aachar papad aur rice',
    },
    {
      name: 'Rajsathan tiffin',
      category: 'Rajsathan tiffin',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Rajsthani',
      rating: 4.8,
      numReviews: 17,
      description: 'Dal roti 5 sabji aachar papad aur rice',
    },
    {
      name: 'tiffin tika',
      category: 'Rajsthani',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Rajsthani',
      rating: 4.5,
      numReviews: 14,
      description: 'Dal roti 5 sabji aachar papad aur rice',
    },
    {
      name: 'tiffin tika',
      category: 'Rajsthani',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Rajsthani',
      rating: 4.5,
      numReviews: 14,
      description: 'Dal roti 5 sabji aachar papad aur rice',
    },
    {
      name: 'tiffin tika',
      category: 'Rajsthani',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Rajsthani',
      rating: 4.5,
      numReviews: 14,
      description: 'Dal roti 5 sabji aachar papad aur rice',
    },
  ],
};
export default data;
