const data = {
  products: [
    {
      _id: '1',
      name: 'Punjabi Tiffin',
      category: 'Punjabi Tiffin',
      image: '/images/p1.jpg',
      price: 60,
      countInStock: 10,
      brand: 'Punjabi Tiffin',
      rating: 4.5,
      numReviews: 10,
      description: 'Dal roti 5 nos sabji rice papad salad aachar',
    },
    {
      _id: '2',
      name: 'Gujrati tiffin',
      category: 'Gujrati tiffin',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Gujrati tiffin',
      rating: 4.0,
      numReviews: 10,
      description: 'Dal roti 5 nos sabji rice papad salad aachar',
    },
    {
      _id: '3',
      name: 'Rajsthani tiffin',
      category: 'Rajsthani tiffin',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Rajsthani tiffin',
      rating: 4.8,
      numReviews: 17,
      description: 'Dal roti 5 nos sabji rice papad salad aachar',
    },
    {
      _id: '4',
      name: 'Rajsthani tiffin',
      category: 'Rajsthani tiffin',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Rajsthani tiffin',
      rating: 4.5,
      numReviews: 14,
      description: 'Dal roti 5 nos sabji rice papad salad aachar',
    },
    {
      _id: '5',
      name: 'Rajsthani tiffin',
      category: 'Rajsthani tiffin',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Rajsthani tiffin',
      rating: 4.5,
      numReviews: 10,
      description: 'Dal roti 5 nos sabji rice papad salad aachar',
    },
    {
      _id: '6',
      name: 'Rajsthani tiffin',
      category: 'Rajsthani tiffin',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Rajsthani tiffin',
      rating: 4.5,
      numReviews: 15,
      description: 'Dal roti 5 nos sabji rice papad salad aachar',
    },
  ],
};
export default data;
